# =============================================================================
# projeto-06-barba.conf — PRJNA630025
# =============================================================================
PROJECT_NAME="projeto-06-barba"

SRA_IDS_FILE="data/projeto-06-barba/manifests/sra_ids_projeto-06-barba.txt"
READS_DIR="data/projeto-06-barba/raw/samples"
MANIFEST="data/projeto-06-barba/manifests/manifest_projeto-06-barba.tsv"
METADATA="data/projeto-06-barba/manifests/metadata_projeto-06-barba.tsv"
OUTDIR="results/projeto-06-barba"
CLASSIFIER="refs/silva-138-99-515-806-nb-classifier.qza"

SEQ_MODE="paired"

THREADS=10
TRUNC_F=270
TRUNC_R=240
TRIM_F=17
TRIM_R=20
MAX_EE_F=2
MAX_EE_R=7

SAMPLING_DEPTH=35000       # mínimo non-chimeric: SRR11851975 com 36.279
