# =============================================================================
# projeto-06-fungos.conf — PRJNA630025
# =============================================================================
PROJECT_NAME="projeto-06-fungos"

SRA_IDS_FILE="data/projeto-06-fungos/manifests/sra_ids_projeto-06-fungos.txt"
READS_DIR="data/projeto-06-fungos/raw/samples"
MANIFEST="data/projeto-06-fungos/manifests/manifest_projeto-06-fungos.tsv"
METADATA="data/projeto-06-fungos/manifests/metadata_projeto-06-fungos.tsv"
OUTDIR="results/projeto-06-fungos"
CLASSIFIER="refs/unite-classifier.qza"    # requer classificador UNITE para fungos

SEQ_MODE="paired"

THREADS=10
TRUNC_F=0                  # sem truncagem — amplicons ITS variam em tamanho
TRUNC_R=0
TRIM_F=18                  # primer ITS3-KYO1 = 18 bp
TRIM_R=20                  # primer ITS4 = 20 bp
MAX_EE_F=2
MAX_EE_R=2

SAMPLING_DEPTH=10000
