# =============================================================================
# template.conf — Configuração de projeto para run_pipeline.sh
# Copie este arquivo: cp auto-bash/configs/template.conf auto-bash/configs/projeto-XX.conf
# =============================================================================
# projeto PRJNA1054347
# Nome do projeto (usado nos logs e relatórios)
PROJECT_NAME="projeto-03"

# Caminhos
SRA_IDS_FILE="data/projeto-03/manifests/sra_ids_projeto-03.txt"
READS_DIR="data/projeto-03/raw/samples"
MANIFEST="data/projeto-03/manifests/manifest_projeto-03.tsv"
METADATA="data/projeto-03/manifests/metadata_projeto-03.tsv"
OUTDIR="results/projeto-03"
CLASSIFIER="refs/silva-138-99-515-806-nb-classifier.qza"

# Sequenciamento
SEQ_MODE="single"          # paired ou single

# Parâmetros DADA2
THREADS=16
TRUNC_F=215                # Truncar Forward em X bp
TRUNC_R=0                # Truncar Reverse em X bp
TRIM_F=20                   # Remover X bp do início Forward
TRIM_R=0                   # Remover X bp do início Reverse
MAX_EE_F=2                 # Max erros esperados Forward
MAX_EE_R=2                 # Max erros esperados Reverse

# Diversidade
SAMPLING_DEPTH=48000        # Profundidade de rarefação (ver denoising-stats.qzv)
