# =============================================================================
# template.conf — Configuração de projeto para run_pipeline.sh
# Copie este arquivo: cp auto-bash/configs/template.conf auto-bash/configs/projeto-XX.conf
# =============================================================================
# projeto PRJNA932786
# Nome do projeto (usado nos logs e relatórios)
PROJECT_NAME="projeto-05"

# Caminhos
SRA_IDS_FILE="data/projeto-05/manifests/sra_ids_projeto-05.txt"
READS_DIR="data/projeto-05/raw/samples"
MANIFEST="data/projeto-05/manifests/manifest_projeto-05.tsv"
METADATA="data/projeto-05/manifests/metadata_projeto-05.tsv"
OUTDIR="results/projeto-05"
CLASSIFIER="refs/silva-138-99-515-806-nb-classifier.qza"

# Sequenciamento
SEQ_MODE="paired"          # single: amplicon V3-V4 ~466bp não permite overlap com 2x250

# Parâmetros DADA2
THREADS=10
TRUNC_F=230                # min read após TRIM = 245-20 = 225 bp (qualidade Q37)
TRUNC_R=210                # não usado em single-end
TRIM_F=19                  # primer 341F = 20 bp (ACTCCTACGGGNGGCWGCAG)
TRIM_R=20                   # não usado em single-end
MAX_EE_F=2                 # Max erros esperados Forward
MAX_EE_R=5                 # não usado em single-end

# Diversidade
SAMPLING_DEPTH=70000        # Profundidade de rarefação (ver denoising-stats.qzv)
