# =============================================================================
# template.conf — Configuração de projeto para run_pipeline.sh
# Copie este arquivo: cp auto-bash/configs/template.conf auto-bash/configs/projeto-XX.conf
# =============================================================================
# projeto PRJNA1155845
# Nome do projeto (usado nos logs e relatórios)
PROJECT_NAME="projeto-09"

# Caminhos
SRA_IDS_FILE="data/projeto-09/manifests/sra_ids_projeto-09.txt"
READS_DIR="data/projeto-09/raw/samples"
MANIFEST="data/projeto-09/manifests/manifest_projeto-09.tsv"
METADATA="data/projeto-09/manifests/metadata_projeto-09.tsv"
OUTDIR="results/projeto-09"
CLASSIFIER="refs/silva-138-99-515-806-nb-classifier.qza"

# Sequenciamento
SEQ_MODE="paired"          # V4 (515F/806R), 2x251 bp, overlap ~35 bp

# Parâmetros DADA2
THREADS=10
TRUNC_F=165                # queda abrupta de qualidade após bp 165 (Q34 flat até aqui)
TRUNC_R=135                # queda após bp 130; 135 inclui margem; overlap = 35 bp
TRIM_F=25                  # 6 bp pad + 515F (19 bp) = 25 bp total
TRIM_R=26                  # 6 bp pad + 806R (20 bp) = 26 bp total
MAX_EE_F=2                 # Max erros esperados Forward
MAX_EE_R=2                 # Max erros esperados Reverse

# Diversidade
SAMPLING_DEPTH=10000        # definir após denoising-stats.qzv
